app/api/forms.py
'''
Created on 20171029

@author: zhou
'''

from wtforms import StringField, SubmitField, validators, PasswordField, TextAreaField,BooleanField, SelectField, FileField
from wtforms.validators import Required, EqualTo, Length, Regexp, Email, DataRequired
from flask_wtf import Form
from werkzeug.routing import ValidationError
from ..models import Role, User
from flask_pagedown.fields import PageDownField
from wtforms.validators import Regexp

class QueryIPForm(Form):
    search = StringField('Search for IP', validators=[DataRequired(),
                                                      Regexp('^((?:(2[0-4]\d)|(25[0-5])|([01]?\d\d?))\.){3}(?:(2[0-4]\d)|(255[0-5])|([01]?\d\d?))$',0,"Invalid IP")])
    submit = SubmitField('Query It')
    #submit2 = SubmitField('Check IP Detail')

class TalkForm(Form):
    body = StringField('', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/api/__init__.py
'''
Created on 20171028

@author: zhou
'''

from flask import Blueprint

api = Blueprint('api', __name__)

from . import views, forms

#from ..models import Permission

app/api/views.py
'''
Created on 20171029

@author: zhou
'''

from .forms import QueryIPForm, TalkForm
from flask import render_template, session, redirect, url_for, current_app,flash, abort,request, make_response, g
from flask import Response, jsonify
from . import api
from queryIP import queryip
from query_lat_long import query_lat_long
from onlineusers import mark_online, get_online_users, get_user_last_activity
from flask_login import login_required
from flask_login.utils import current_user
from ..decorators import admin_required, permission_required
from check_mobile import checkMobile
from todayonhistory import todayonhistory
from talk_robot import talkrobot
import time, json
#from pymongo import MongoClient
from mongo_conn import Mongo_Conn

@api.route('/api/todayonhistory/enevts/<m>/<d>', methods=['GET', 'POST'])
def querytoday(m, d):
    history = todayonhistory(m, d)
    his = history['Events']
    return render_template('api/todayonhistory.html', his=his)

@api.route('/api/talk-robot/<info>/<roomid>', methods=['GET', 'POST'])
def talk(info,roomid):
    db = Mongo_Conn()
    t = time.strftime("%Y-%m-%d %X", time.localtime())
    content = talkrobot(info)
    rooms = db[roomid]
    rooms.insert({"robotsay":content,"yousay":info, "time":t})
    cc = {"robotsay":content,"yousay":info, "time":t}
    return content
    #return json.dumps(cc)
    # return jsonify(
    #     {'text': 'haha'}
    # )
    #return render_template('api/talk_robot.html', content=content)


@api.route('/api/talkrobot', methods=['GET', 'POST'])
def talk_robot():
    db = Mongo_Conn()
    t = time.strftime("%Y-%m-%d %X", time.localtime())
    room = "R" + str(t)
    rooms = db[room]
    rooms.insert({"robotsay":"","yousay":"","time":t})
    form = TalkForm()
    # if form.validate_on_submit():
    #     info = form.body.data
    #     content = talkrobot(info)
    #     return content
        #return render_template('api/talk.html', form=form, content=content, t=t)
    return render_template('api/talk.html',form=form, t=t, room=room)

@api.before_app_request
def checkmobile():
    MB = False
    if checkMobile(request):
        MB = True

@api.route('/api/query-ip', methods=['GET', 'POST'])
def query_ip():
    form = QueryIPForm()
    if form.validate_on_submit():
        ip = form.search.data
        #return redirect('http://maps.google.com/?ip=%s' % ip)
        return redirect(url_for('.ip_detail',ip=ip))
    return render_template('api/query_ip.html',form=form)

# @api.route('/api/ip-detail/<ip>')
# def ip_detail(ip):
#     ip = queryip(ip)
#     countryName = ip['countryName']
#     countryCode = ip['countryCode']
#     stateProv = ip['stateProv']
#     continentName = ip['continentName']
#     ipAddress = ip['ipAddress']
#     city = ip['city']
#     continentCode = ip['continentCode']
#     location = query_lat_long(countryName,countryCode)
#     if len(location['locations']) != 0:
#         lat = location['locations'][0]['latitude']
#         lon = location['locations'][0]['longitude']
#         return render_template('api/ip_detail.html', countryName=countryName,
#                            countryCode=countryCode, stateProv=stateProv,
#                            continentName=continentName, ipAddress=ipAddress,
#                            city=city, continentCode=continentCode,
#                            lat=lat, lon=lon)
#     return render_template('api/ip_detail.html', countryName=countryName,
#                                countryCode=countryCode, stateProv=stateProv,
#                                continentName=continentName, ipAddress=ipAddress,
#                                city=city, continentCode=continentCode,
#                            lat=0,lon=0)
    #return render_template('api/ip_detail.html',ip=ip)

@api.route('/api/ip-detail/<ip>')
def ip_detail(ip):
    ip = queryip(ip)
    ipAddress = ip['ip']
    ip_is_available = ip['valid']
    YIP = request.headers.get('X-Forwarded-For',request.remote_addr)
    if ip['valid'] == True:
        countryName = ip['country']
        countryCode = ip['country_code']
        region = ip['region']
        #continentName = ip['continent_code']
        ipAddress = ip['ip']
        city = ip['city']
        continentCode = ip['continent_code']
        lat = ip['latitude']
        lon = ip['longitude']
        # location = query_lat_long(countryName,countryCode)
        # if len(location['locations']) != 0:
    #   lat = location['locations'][0]['latitude']
    #   lon = location['locations'][0]['longitude']
        return render_template('api/ip_detail.html', countryName=countryName,
                            countryCode=countryCode, region=region,
                            ipAddress=ipAddress,ip_is_available=ip_is_available,
                            city=city, continentCode=continentCode,
                            lat=lat, lon=lon,YIP=YIP)
    return render_template('api/ip_detail.html', countryName='',
                               countryCode='', region='',
                               ipAddress=ipAddress,lat=0, lon=0,
                               city='', continentCode='',ip_is_available=ip_is_available,
                           YIP=YIP)


@api.before_app_request
def mark_current_user_online():
    if request.headers.get('X-Forwarded-For'):
        mark_online(request.headers['X-Forwarded-For'])
    else:
        mark_online(request.remote_addr)

@api.route('/api/online-user')
@login_required
@admin_required
def online_user():
    Online_user = get_online_users()
    for i in Online_user:
        location = queryip(i)
        city = location.get('city','kenya')
        return render_template('api/online_user.html', Online_user=Online_user, city=city)
    #return Response('Online User: %s' % ','.join(get_online_users()), mimetype='text/plain')
@api.route('/api/online-info')
def online_info():
    #raise Exception('test')
    apiua = request.headers
    return Response('Online Info: %s' % apiua)

@api.route('/api/check-mobile')
def check_mobile():
    if checkMobile(request):
        return 'Mobile'
    else:
        return 'PC'

app/templates/api/ip_detail.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block page_content %}
<div class="container">
<h2 style="color: #1b1b1b">IP address {{ ipAddress }}</h2>
<div class="row" style="color: #0e0e0e">
    <div class="col-lg-6 col-md-6">
        <table class="table table-striped">
            <tbody>
            <tr>
                <th>countryName</th>
                <td>{{ countryName }}</td>
            </tr>
            <tr>
                <th>countryCode</th>
                <td>{{ countryCode }}</td>
            </tr>
            <tr>
                <th>region</th>
                <td>{{ region }}</td>
            </tr>
{#            <tr>#}
{#                <th>continentName</th>#}
{#                <td>{{ continentName }}</td>#}
{#            </tr>#}
            <tr>
                <th>city</th>
                <td><a href="https://www.google.com/maps?q={{ city }}" >{{ city }}</a></td>
            </tr>
            <tr>
                <th>continentCode</th>
                <td>{{ continentCode }}</td>
            </tr>
            <tr>
                <th>Coordinates</th>
                <td>{{ lat }},{{ lon }}</td>
            </tr>
             <tr>
                <th>IP Is Available Or Not</th>
                <td>{{ ip_is_available }}</td>
            </tr>
             <tr>
                <th>Your IP</th>
                <td>{{ YIP }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="col-lg-6 col-md-6">
        <div>
            <!--<iframe style="width:100%; height:500px; border:none; margin:0; padding:0"
                    src="//www.openstreetmap.org/export/embed.html?bbox=34.3219,-3.79207,39.3219,1.20793&amp;layer=mapnik&amp;marker=-1.29207,36.8219">

            </iframe>-->
            <!--<iframe src="https://www.google.com/maps/embed?pb=kenya" width="600" height="450" frameborder="0" style="border:0" allowfullscreen>

            </iframe>-->
            <iframe style="width:100%; height:500px; border:none; margin:0; padding:0"
                    src="//www.openstreetmap.org/export/embed.html?bbox={{ lon - 2 }},{{ lat - 2 }},{{ lon + 2 }},{{ lat + 2 }}&layer=mapnik&marker={{ lat }},{{ lon }}">

            </iframe>
        </div>
    </div>
</div>
 <div>
     This Result Provided By <a href="https://db-ip.com/"> DB-IP.com.</a>
 </div>
</div>
<!--<div><a href="http://maps.google.com/?ip=">Check IP Detail</a></div>-->

{% endblock %}

app/templates/api/online_user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}
{% block title %}
Flask-OnlineUser
{% endblock %}

{% block page_content %}
<div class="page-header" style="color: #000;">
    <h1>Online Users:</h1>
    {% for i in Online_user %}
        <li style="color: #f0f0f0;"><a href="{{ url_for('api.ip_detail', ip=i) }}" >{{ i }}</a></li>
    {% endfor %}


</div>
{% endblock %}

app/templates/api/query_ip.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block page_content %}
 <div>
{{ wtf.quick_form(form) }}
</div>


{% endblock %}

app/templates/api/talk.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}
Talk With Robot
{% endblock %}

{% block page_content %}

    <div id="room_online_user" class="user_status">
        <p>Talk With Robot</p>
        <div class="user_list">
        <span>Robot</span>
        </div>
    </div>

<style>
tbody {
    display: table-row-group;
    vertical-align: middle;
    border-color: inherit;
}
</style>

<script>
function loadXMLDoc() {
    var xmlhttp;
    var form = new FormData(document.getElementById("post_content"));
    var content = document.getElementById("myInput").value;
    var rooms = document.getElementById("room").innerHTML;
   if (window.XMLHttpRequest)
   {
        xmlhttp=new XMLHttpRequest();
    }
   else
   {
       xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
   xmlhttp.onreadystatechange=function () {
        if (xmlhttp.readyState==4 && xmlhttp.status==200)
        {
            myObj = JSON.parse(this.responseText);
{#            document.getElementById("initSpan").innerHTML=xmlhttp.responseText;#}
            $("#content").append('<tbody> <tr valign="top"> <td> <font color="#999999">{{ t }}</font> </td> <td id="td1"><b>You :</b> <span id="mySpan"></span></td> </tr> </tbody> </table>').attr("span").text(myObj.yousay);
{#            $("#td1").children("span").attr("id","mySpan" + ($("span").length +1) )#}
            $("#content").append('<tbody> <tr valign="top"> <td> <font color="#999999">{{ t }}</font> </td> <td id="td2"><b>Duck :</b> <span id="duckSpan"></span></td> </tr> </tbody> </table>').attr("span").text(myObj.robotsay);
{#            $("#td2").children("span").attr("id","duckSpan" + ($("span").length +1) )#}
{#            document.getElementById("mySpan").innerHTML = myObj.yousay;#}
{#            $("#td1").children("span").text(myObj.yousay);#}
{#            $("#td2").children("span").text(myObj.robotsay);#}
{#            document.getElementById("duckSpan").innerHTML = myObj.robotsay;#}
{#            $("#content").clone().attr("id", "initSpan" + ($("span").length + 1)).insertAfter($("#content")).text(myObj.yousay);#}
{#            $("#content").clone().attr("id", "initSpan" + ($("span").length + 1)).insertAfter($("#content")).text(myObj.robotsay);#}
        }
    }
    xmlhttp.open("GET", "/api/talk-robot/" + content + "/" + rooms, true);
    xmlhttp.send();
}
function reset(){
    document.getElementById("myInput").reset();
}
</script>
<div id="room">{{ room }}</div>
    <div id="ChatContainer">
    <div id="messages">
        <table id="content" cellpadding="0" cellspacing="0">
            <tbody>
            <tr valign="top">
                <td>
                    <font color="#999999">{{ t }}</font>
                </td>
                <td><b>Duck :</b> <span id="initSpan">HELLO</span></td>
            </tr>
            </tbody>
        </table>
    </div>

    </div>

    <br>
    <br>
{#	<form action="{{ url_for('api.talk_robot') }}" method="POST" id="post_content">#}
    <form method="POST" id="post_content">
		<input id="myInput" name="content" type="TEXT" style="width:300px"/>
		<input type="hidden" name="room_id" />
		<input type="button" value="发言" onclick="loadXMLDoc(reset)"/>
	</form>

{#      <form action="" method="post" name="submit">#}
{#      {{ form.hidden_tag() }}#}
{#      <p>#}
{#          Please enter your message:<br>#}
{#          {{ form.body(size=80) }}<br>#}
{#          {% for error in form.body.errors %}#}
{#            <span style="color: red;">[{{ error }}]</span>#}
{#          {% endfor %}<br>#}
{#      </p>#}
{#      <p><input type="submit" value="Submit" onclick="loadXMLDoc()"></p>#}
{#  </form>#}
{#    <div>#}
{#    {{ wtf.quick_form(form) }}#}
{#    </div>#}
{% endblock %}

app/templates/api/talk_robot.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block page_content %}
<div>
{{ content }}

</div>


{% endblock %}

app/templates/api/todayonhistory.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block page_content %}

 <div>
{% for i in his %}
 <div>
 <h3>YEAR: {{ i['year'] }}</h3>
 <h4>{{ i['text'] }}</h4>
 <h4>
     <h4>KEY WORD</h4>
     {% for j in i['links'] %}
      <div>
      <h5>
          <a href="{{ j['link'] }}">{{ j['title'] }}</a>
      </h5>
      </div>
     {% endfor %}
 </h4>
 </div>
 {% endfor %}

</div>


{% endblock %}